name: driftekhar_patient
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  easy_date_timeline: ^1.1.3
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_calendar_week: ^2.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  flutter_toastr: ^1.0.3
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  # isar: ^3.1.0+1
  # isar_flutter_libs: ^3.1.0+1
  # isar_flutter_libs:
  #   git: 
  #     url: https://github.com/MrLittleWhqite/isar_flutter_libs.git
  logger: ^2.0.2+1
  marquee: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  rename: ^3.0.2
  riverpod_annotation: ^2.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  doc_patient_libs:
    git:
      url: https://github.com/anasmj/doc_patient_libs
      ref: main  
  cloud_firestore: ^5.5.0
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  import_sorter: ^4.6.0
  custom_lint: ^0.5.6
  # isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.6
  flutter_gen_runner: ^5.8.0

dependency_overrides:
  # analyzer: "<=6.0.0"
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/service.images/
    - assets/icons/
    - assets/texts/services/


flutter_gen:
  output: lib/src/gen/ 
  integrations:
    flutter_svg: true
  

 


import_sorter:
  comments: false
