name: driftekhar_patient
description: "An app that will help patient to book an appointment with a doctor."
publish_to: 'none'
#update version code in app drawer as well
version: 0.1.0+10

environment:
  sdk: ^3.5.3

dependencies:
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  firebase_core: ^3.7.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  intl: ^0.19.0
  logger: ^2.0.2+1
  marquee: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  riverpod_annotation: ^2.3.1
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  doc_patient_libs:
    git:
      url: https://github.com/anasmj/doc_patient_libs
      ref: main  
  cloud_firestore: ^5.5.0
  flutter_local_notifications: ^18.0.1
  device_info_plus: ^11.1.1
  http: ^1.2.2
  googleapis_auth: ^1.6.0
  googleapis: ^13.2.0
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.3
  dotted_border: ^2.1.0
  lottie: ^3.3.0
  youtube_player_flutter: ^9.1.1
  firebase_auth: ^5.3.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fluttertoast: ^8.2.10


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.6
  # import_sorter: ^4.6.0
  # custom_lint: ^0.5.6
  # isar_generator: ^3.1.0+1
  riverpod_generator: ^2.3.6
  # flutter_gen_runner: ^5.8.0

dependency_overrides:
  # analyzer: "<=6.0.0"
  

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/jpg/
    - assets/images/png/
    - assets/images/service.images/
    - assets/icons/
    - assets/texts/services/
    - assets/lotties/
    - assets/fonts/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/NotoSans-VariableFont_wdth,wght.ttf
          weight: 700


flutter_gen:
  output: lib/src/gen/ 
  integrations:
    flutter_svg: true
  

 
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/app.icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/app.icon.png"

import_sorter:
  comments: false
